# Generated by Django 5.1 on 2024-08-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0002_remove_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='author',
            name='date_of_death',
        ),
        migrations.AlterField(
            model_name='product',
            name='genre',
            field=models.ManyToManyField(to='acervo.genre'),
        ),
        migrations.AlterField(
            model_name='product',
            name='summary',
            field=models.TextField(max_length=1000),
        ),
    ]
